name: advance_flutter_course
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  # State management
  flutter_bloc: ^8.1.6
  # Code generator (mainly used with cubit & retrofit)
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  # For Dependency Injection
  get_it: ^8.0.1
  # Automatically generate code for converting to and from JSON by annotating Dart classes.
  json_serializable: ^6.8.0
  json_annotation: ^4.9.0
  # Networking (APIs).
  dio: ^5.7.0
  retrofit: ^4.4.1
  retrofit_generator: ^9.1.4
  pretty_dio_logger: ^1.4.0
  # Localizations
  intl: ^0.19.0
  easy_localization: ^3.0.7
  # Splash Screen
  flutter_native_splash: ^2.4.2
  # An SVG rendering and widget library for Flutter, which allows painting.
  flutter_svg: ^2.0.10+1
  # A flutter plugin for adapting screen and font size.
  flutter_screenutil: ^5.9.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  assets:
    - assets/svgs/
    - assets/images/

